const Event = require("../models/Event");

const guidePhoneByDepartment = {
  Technical: "+91 75880 12633",
  "Non-Technical": "+91 75880 12633",
  Workshops: "+91 75880 12633",
};

const eventsSeed = [
  {
    eventId: "dummy-codestorm",
    department: "Technical",
    title: "CodeStorm",
    shortDescription: "24-hour hackathon where teams build innovative solutions to real-world problems.",
    displayCategory: "Technical",
    displayTeamSize: "2-4",
    displayPrize: "₹50,000",
    displayDeadline: "March 10, 2026",
    description: "24-hour hackathon where teams build innovative solutions to real-world problems.",
    isTeamEvent: true,
    teamSize: 4,
    fee: 0,
    address: "Main Auditorium",
    time: "March 10, 2026 | 9:00 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-robowar",
    department: "Technical",
    title: "RoboWar",
    shortDescription: "Build and battle robots in an arena. Last bot standing wins!",
    displayCategory: "Technical",
    displayTeamSize: "3-5",
    displayPrize: "₹30,000",
    displayDeadline: "March 8, 2026",
    description: "Build and battle robots in an arena. Last bot standing wins!",
    isTeamEvent: true,
    teamSize: 5,
    fee: 0,
    address: "Robotics Arena",
    time: "March 8, 2026 | 10:00 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-ai-ideathon",
    department: "Technical",
    title: "AI Ideathon",
    shortDescription: "Pitch AI-powered solutions to a panel of industry judges.",
    displayCategory: "Technical",
    displayTeamSize: "2-3",
    displayPrize: "₹25,000",
    displayDeadline: "March 10, 2026",
    description: "Pitch AI-powered solutions to a panel of industry judges.",
    isTeamEvent: true,
    teamSize: 3,
    fee: 0,
    address: "Innovation Lab",
    time: "March 10, 2026 | 2:00 PM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-paper-presentation",
    department: "Technical",
    title: "Paper Presentation",
    shortDescription: "Present your research papers on cutting-edge technology topics.",
    displayCategory: "Technical",
    displayTeamSize: "1-2",
    displayPrize: "₹15,000",
    displayDeadline: "March 7, 2026",
    description: "Present your research papers on cutting-edge technology topics.",
    isTeamEvent: true,
    teamSize: 2,
    fee: 0,
    address: "Seminar Hall A",
    time: "March 7, 2026 | 10:30 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-quiz",
    department: "Non-Technical",
    title: "Quiz",
    shortDescription: "Test your knowledge across science, tech, and general awareness.",
    displayCategory: "Non-Technical",
    displayTeamSize: "2",
    displayPrize: "₹10,000",
    displayDeadline: "March 12, 2026",
    description: "Test your knowledge across science, tech, and general awareness.",
    isTeamEvent: true,
    teamSize: 2,
    fee: 0,
    address: "Room 201",
    time: "March 12, 2026 | 11:00 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-ui-battle",
    department: "Technical",
    title: "UI Battle",
    shortDescription: "Design stunning interfaces in a timed design sprint.",
    displayCategory: "Technical",
    displayTeamSize: "1",
    displayPrize: "₹15,000",
    displayDeadline: "March 10, 2026",
    description: "Design stunning interfaces in a timed design sprint.",
    isTeamEvent: false,
    teamSize: 1,
    fee: 0,
    address: "Design Lab",
    time: "March 10, 2026 | 10:00 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-gaming-tournament",
    department: "Non-Technical",
    title: "Gaming Tournament",
    shortDescription: "Compete in Valorant, CS2, and FIFA in our esports arena.",
    displayCategory: "Non-Technical",
    displayTeamSize: "1-5",
    displayPrize: "₹20,000",
    displayDeadline: "March 12, 2026",
    description: "Compete in Valorant, CS2, and FIFA in our esports arena.",
    isTeamEvent: true,
    teamSize: 5,
    fee: 0,
    address: "Gaming Arena",
    time: "March 12, 2026 | 3:00 PM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-circuit-design",
    department: "Technical",
    title: "Circuit Design",
    shortDescription: "Design and prototype electronic circuits under time pressure.",
    displayCategory: "Technical",
    displayTeamSize: "2",
    displayPrize: "₹15,000",
    displayDeadline: "March 8, 2026",
    description: "Design and prototype electronic circuits under time pressure.",
    isTeamEvent: true,
    teamSize: 2,
    fee: 0,
    address: "Electronics Lab",
    time: "March 8, 2026 | 11:00 AM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-webdev-sprint",
    department: "Workshops",
    title: "WebDev Sprint",
    shortDescription: "Build a complete web application from scratch in 6 hours.",
    displayCategory: "Workshops",
    displayTeamSize: "1-2",
    displayPrize: "₹15,000",
    displayDeadline: "March 10, 2026",
    description: "Build a complete web application from scratch in 6 hours.",
    isTeamEvent: true,
    teamSize: 2,
    fee: 0,
    address: "CS Lab 3",
    time: "March 10, 2026 | 2:00 PM",
    guide: "TechFest Team",
  },
  {
    eventId: "dummy-data-science-challenge",
    department: "Workshops",
    title: "Data Science Challenge",
    shortDescription: "Analyze datasets and build predictive models to solve problems.",
    displayCategory: "Workshops",
    displayTeamSize: "2-3",
    displayPrize: "₹20,000",
    displayDeadline: "March 10, 2026",
    description: "Analyze datasets and build predictive models to solve problems.",
    isTeamEvent: true,
    teamSize: 3,
    fee: 0,
    address: "CS Lab 1",
    time: "March 10, 2026 | 10:00 AM",
    guide: "TechFest Team",
  },
];

async function seedEventsIfEmpty() {
  if (String(process.env.ENABLE_EVENT_SEED || "").toLowerCase() !== "true") {
    return;
  }

  await Promise.all(
    eventsSeed.map((event) =>
      Event.updateOne(
        { eventId: event.eventId },
        {
          $set: {
            ...event,
            guidePhone: event.guidePhone || guidePhoneByDepartment[event.department] || "N/A",
          },
        },
        { upsert: true }
      )
    )
  );
}

module.exports = { eventsSeed, seedEventsIfEmpty };
